import { BadRequestException, HttpException, Injectable, InternalServerErrorException, NotFoundException } from '@nestjs/common';
import { CreateArticuloDto } from './dto/create-articulo.dto';
import { UpdateArticuloDto } from './dto/update-articulo.dto';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Articulo } from './entities/articulo.entity';

@Injectable()
export class ArticuloService {

  constructor(
    @InjectRepository(Articulo)
    private articuloRepository: Repository<Articulo>
  ) { }

  async createArticulo(createArticuloDto: CreateArticuloDto) {
    try {
      const newArticulo = this.articuloRepository.create(createArticuloDto);
      return await this.articuloRepository.save(newArticulo);
    } catch (error) {
      throw new InternalServerErrorException(
        'Ocurri칩 un error al guardar el art칤culo'
      );
    }
  }

  async getArticulos() {
    try {
      return await this.articuloRepository.find({
        relations: ["idCategoria2", "idMarca2", "idCondicionProducto2"],
        select: {
          idCategoria2: {
            idCategoria: true,
            nombre: true,
          },
          idMarca2: {
            idMarca: true,
            nombre: true,
          },
          idCondicionProducto2: {
            idCondicionProducto: true,
            nombre: true,
          },
        },
      });
    } catch (error) {
      throw new InternalServerErrorException(
        'Ocurri칩 un error al obtener los art칤culos',
      );
    }
  }

  async getArticulo(id: number) {
    try {
      const agendaFound = await this.articuloRepository.findOne({
        where: { idArticulo: id },
        relations: ["idCategoria2", "idMarca2", "idCondicionProducto2"],
        select: {
          idCategoria2: {
            idCategoria: true,
            nombre: true,
          },
          idMarca2: {
            idMarca: true,
            nombre: true,
          },
          idCondicionProducto2: {
            idCondicionProducto: true,
            nombre: true,
          },
        },
      });
      if (!agendaFound) {
        throw new NotFoundException('Art칤culo no encontrado');
      }

      return agendaFound;
    }
    catch (error) {
      throw new InternalServerErrorException('Error interno al obtener el art칤culo.');
    }
  }

  async updateArticulo(idArticulo: number, updateArticuloDto: UpdateArticuloDto) {
    try {
      const agendaFound = await this.articuloRepository.findOneBy({ idArticulo });

      if (!agendaFound) {
        throw new NotFoundException(`Agenda con ID ${idArticulo} no encontrada`);
      }

      const updatedAgenda = Object.assign(agendaFound, updateArticuloDto);

      return await this.articuloRepository.save(updatedAgenda);
    } catch (error) {

      if (error.code === 'ER_DUP_ENTRY') {
        throw new BadRequestException('Ya existe una agenda con esos datos.');
      }
      throw new InternalServerErrorException('Error interno al actualizar la agenda.');
    }
  }

  async updateEstadoArticulo(idArticulo: number, updateEstadoArticuloDto: any) {
    try {
      const articuloFound = await this.articuloRepository.findOneBy({ idArticulo });
      if (!articuloFound) {
        throw new NotFoundException(`Art칤culo con ID ${idArticulo} no encontrado`);
      }
      const updatedArticulo = Object.assign(articuloFound, updateEstadoArticuloDto);
      return await this.articuloRepository.save(updatedArticulo);
    } catch (error) {
      if (error.code === 'ER_DUP_ENTRY') {
        throw new BadRequestException('Ya existe un art칤culo con esos datos.');
      }
      throw new InternalServerErrorException('Error interno al actualizar el art칤culo.');
    }
  }

  async deleteArticulo(idArticulo: number) {
    try {
      const deleteResult = await this.articuloRepository.delete(idArticulo);
      if (deleteResult.affected === 0) {
        throw new NotFoundException(`Art칤culo con ID ${idArticulo} no encontrado`);
      }
      return { message: `Art칤culo con ID ${idArticulo} eliminado correctamente` };
    } catch (error) {
      // 游녤 Si ya es una excepci칩n HTTP (como NotFoundException), la relanzamos
      if (error instanceof HttpException) {
        throw error;
      }

      // Errores de conexi칩n a la base de datos
      if (error.code === 'ECONNREFUSED' || error.code === 'PROTOCOL_CONNECTION_LOST') {
        throw new InternalServerErrorException('No se pudo conectar a la base de datos.');
      }
      throw new InternalServerErrorException('Error interno al eliminar el art칤culo.');
    }
  }
}
